apiVersion: v1
kind: Pod
metadata:
  name: pod-with-node-selector
  labels:
    run: pod-with-node-selector
spec:
  containers:
    - name: nginx
      image: nginx

  dnsPolicy: ClusterFirst
  restartPolicy: Always

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: accelerator
                operator: In
                values:
                  - nvidia-tesla-p100