apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-with-node-name
  name: pod-with-node-name
spec:
  containers:
  - image: nginx
    name: pod-with-node-name
    resources: {}
  nodeName: minikube
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
